image:
  registry: docker.io
  repository: jamshidk/odoo
  tag: "17.0"
  digest: ""

persistence:
  enabled: true
  resourcePolicy: ""
  storageClass: "standard-rwo"
  accessModes:
    - ReadWriteOnce

  accessMode: ReadWriteOnce
  size: 10Gi

  
##
postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "standard-rwo" # Specify your custom StorageClass
      size: 10Gi                         # Customize the storage size
      accessModes:
        - ReadWriteOnce
